eval_metric: auc

mlp_parameters:
  lr: 0.01
  num_layers: 2
  hidden_channels: 64
  dropout: 0.0
  batchnorm: false
  l2: 5e-7

gcn_parameters:
  lr: 0.01
  num_layers: 2
  hidden_channels: 64
  dropout: 0.0
  batchnorm: false
  l2: 5e-7

sage_parameters:
  lr: 0.01
  num_layers: 2
  hidden_channels: 64
  dropout: 0
  batchnorm: false
  l2: 5e-7