pretrained: false
checkpoint: "checkpoints/elliptic_model.pt"

model:
  type: "GCN"
  params:
    hidden_channels: 64
    out_channels: 32
    num_layers: 5
    dropout: 0.5
    # layer_heads: [4, 4, 1] # for GAT
    batchnorm: true